export const ALL_ROLE = ['ROLE_ADMIN', 'ROLE_USER', 'ROLE_TEACHER', 'ROLE_BOSS'];
export const NOT_USER = ['ROLE_ADMIN', 'ROLE_TEACHER', 'ROLE_BOSS'];
export const NOT_USER_AND_TEACHER = ['ROLE_ADMIN', 'ROLE_BOSS'];
